### ISSUE TITLE
Android - React Native Error

### ISSUE THREAD

**Issue by vinh84** [hitz-group/xml-escpos-helper#13]
![image](https://user-images.githubusercontent.com/769541/149610583-b3eb19e9-1790-47e4-b8ae-90d318a2822c.png)

**Comment by rockneverdies55** [comment]
Same here.

**Comment by rockneverdies55** [comment]
@vinhhrv - how did you get around this problem ?

**Comment by rockneverdies55** [comment]
I manually installed pngjs, util, stream and zlib packages in my project as the build complained for them.

After installing zlib now it started crying for missing zlib_bindings module. I guess I'm giving up on this.

**Comment by vinh84** [comment]
@rockneverdies55  End of ReadMe have note

Use this [node-libs-react-native](https://www.npmjs.com/package/node-libs-react-native) if we need to use this library in react native (adds some mock or js implementation for fs, stream etc)

**Comment by rockneverdies55** [comment]
Finally got it to work after installing node-libs-react-native. Thanks a lot.
