### ISSUE TITLE
[question] More documentation

### ISSUE THREAD

**Issue by jeffreyvanhees** [hitz-group/xml-escpos-helper#6]
Hi!

Great package! Especially since you also managed to build in support for images (after your fork). However, I can't find anywhere how to use these xml tags exactly, apart from your example.

Is there a list or documentation available somewhere that elaborates on the features/tags/nodes?

Got it running in react-native, which seems to work well!

Thanks!

**Comment by jeffreyvanhees** [comment]
Is this package actually maintained?

**Comment by lakshmaji-till** [comment]
Hey @jeffreyvanhees, Thanks for comments. Yes, we are actively maintaining. Our team was occupied with internal production releases!
Will come up with instructions in some time. and yes, this library currently supporting images with `png` format! (but there are some limitation with [pngjs](https://www.npmjs.com/package/pngjs) with `react-native` framework)

**Comment by lakshmaji-till** [comment]
We've added some basic examples. You can find out image printing [here](https://github.com/hitz-group/xml-escpos-helper/blob/master/examples/src/printImage.ts).

**Comment by jeffreyvanhees** [comment]
Hi @lakshmaji-till! Great, many thanks!! 👍

**Comment by lakshmaji-till** [comment]
@jeffreyvanhees , glad you find this library useful!

**Comment by jeffreyvanhees** [comment]
Absolutely! We use thermal printers which we control remotely. The 'receipt' is generated via an API. So now we just send them the XML. Thanks to this package it's easy to get the receipt based on XML output.
